redis:
  host: 192.168.1.199
  port: 6379
  password: risesin_199
  pool:
  timeout: 0
  jedis:
    pool:
      max-idle: 100
      max-wait: 1000

# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8083

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: go_ROOT<0
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.199:3306/risesin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    druid:
      initialSize: 1
      maxActive: 10
      minIdle: 1
      maxWait: 60000
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  main:
    allow-bean-definition-overriding: true  # 因有程序中显示有类名一致,但查找又没有,故加此配置可以启动不报错
  application:
    name: risesin-systemuserservice



management:
  health:
    redis:
      enabled: false

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.200:5000/eureka/,http://192.168.1.198:5001/eureka/,http://192.168.1.197:5002/eureka/
  instance:
    prefer-ip-address: true  #访问路径可以显示IP地址


